name: King of Cloa
author: Leilia Faith
website: http://www.github.com/avatarkorra/minecraft-cloaking
main: com.github.avatarkorra.minecraft.kingofcloa.KingOfCloaPlugin
commands: 
    cloak:
        description: Cloak yourself
        usage: /cloak
    location:
        description: stuff with locations
        usage: |
               /<command> <name> [player]
               Example: /<command> blah
    teleport:
        description: Teleport yourself
        usage: |
               /<command> <lat> <lng>
               Example: /<command> 32.25164 -111.01884
    launch:
        description: Launch someone
        usage: |
               /<command> [player]
               Example: /<command> r351574nc3
    lightarrow:
        description: Strike arrow with lightning
        usage: |
               /<command>
               
version: 0.1